[package]
name = "macro_examples"
version = "0.1.0"
authors = ["Jun Wu <quark@lihdd.net>"]
edition = "2018"

[lib]
path = "macro_examples.rs"

[dependencies]
stateful_macro_rules = { path = "../..", features = ["debug"] }